#8003表示注册到zookeeper服务器的支付服务提供者端口号
server:
  port: 8003
#服务别名----注册zookeeper到注册中心名称
spring:
  application:
    name: cloud-payment-zkserver
  cloud:
    zookeeper:
      connect-string: 47.93.18.108:2181
 