server:
  port: 8005
spring:
  application:
    name: consul-provider-servercs
  cloud:
    consul:
      host: 47.93.18.108
      port: 8500
      discovery:
       #hostname: 127.0.0.1
       service-name: ${spring.application.name}
       prefer-ip-address: true
        # 发送心跳
       heartbeat:
        enabled: true