server:
  port: 8001
spring:
  application:
    name: cloud-payment-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource 
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://47.93.18.108:3306/sq?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: sq0418
mybatis:
  mapperLocations: classpath:mappers/*.xml
  type-aliases-package: com.sq.entitys
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  