###consul服务端口号
server:
  port: 8006

spring:
  application:
    name: cloud-consumer-servercs
  ####consul注册中心地址
  cloud:
    consul:
      host: 47.93.18.108
      port: 8500
      discovery:
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}
        prefer-ip-address: true
        # 发送心跳
        heartbeat:
          enabled: true